### ISSUE TITLE
Typehints, neat linting, tests etc.

### ISSUE THREAD

**Issue by IanFooMZ** [IanFooMZ/SonyBayerFilter#20]
All typehints need to be intact.

Files:
- init.py
- etc
- This is a test

**Comment by IanFooMZ** [comment]
#17

**Comment by IanFooMZ** [comment]
https://github.com/IanFooMZ/SonyBayerFilter/issues/7

#8

**Comment by Tyronitar** [comment]
This is something being done as code is written.

Issue doesn't need to exist really, since it's not its own separate task.
